<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="smb"> 

    <xacro:include filename="$(find smb_description)/urdf/smb_utils.urdf.xacro" />
	    
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="robot_name" value="smb"/> 

    <xacro:property name="chassisHeight" value="0.22"/>
    <xacro:property name="chassisLength" value="0.605"/>
    <xacro:property name="chassisWidth" value="0.410"/>
    <xacro:property name="chassisMass" value="40"/>
	
    <xacro:property name="wheelWidth" value="0.17"/>
    <xacro:property name="wheelRadius" value="0.19"/>
    <xacro:property name="frontWheelX" value="0.2159"/>
    <xacro:property name="backWheelX" value="-0.2159"/>
    <xacro:property name="wheelClearance" value="0.03"/>
    <xacro:property name="wheelHeight" value="0.08"/>
    <xacro:property name="wheelMass" value="5"/> 

    <!-- Model macros -->   
    <xacro:macro name="wheel" params="prefix X Y wheel_joint_type">
        <joint name="${prefix}_WHEEL" type="${wheel_joint_type}">
            <parent link="base"/>
            <child link="${prefix}_WHEEL"/>
            <origin xyz="${X} ${Y} ${-wheelHeight}" rpy="${0.5*PI} 0 0" />
            <axis xyz="0 0 -1" rpy="0 0 0" />
            <dynamics damping="1.0" friction="0.0"/>
            <limit effort="1" velocity="1"/>
            <joint_properties damping="0.2" friction="0.2"/>
        </joint>

        <link name="${prefix}_WHEEL">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
                </geometry>
            </collision>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="${wheelMass}"/>
                <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
            </inertial>
        </link>

        <gazebo reference="${prefix}_WHEEL">
            <mu1 value="10"/>
            <mu2 value="0.1"/>
            <fdir1 value="1 0 0"/>
            <kp>10000000.0</kp> 
            <kd>1.0</kd>
            <minDepth>0.005</minDepth>
            <maxVel>100.0</maxVel>
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="chassis">

        <link name="base">
            <collision> 
                <origin xyz="0 0 0" rpy="0 0 0"/> 
                <geometry> 
                    <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/> 
                </geometry> 
            </collision>
            <visual> 
                <origin xyz="0 0 0" rpy="0 0 0"/> 
                <geometry> 
                    <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/> 
                </geometry> 
                <material name="green"/>
            </visual>
        </link>

        <gazebo reference="base">
            <material>Gazebo/Green</material>
        </gazebo>

    <!-- Fixed joint to add dummy inertia link -->
    <joint name="base_to_base_inertia" type="fixed">
      <parent link="base"/>
      <child link="base_inertia"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <!-- Dummy inertia link, because KDL cannot have inertia on the base link -->
    <link name="base_inertia">
      <inertial> 
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${chassisMass}"/> 
        <box_inertia m="${chassisMass}" 
                     x="${chassisLength}" 
                     y="${chassisWidth}"
                     z="${chassisHeight}"/>
      </inertial>  
    </link>

    </xacro:macro>

    <xacro:macro name="smb" params="wheel_joint_type=continuous">
        <chassis/>

        <wheel prefix="LF" X="${frontWheelX}" 
            Y="${chassisWidth/2+wheelClearance+wheelWidth/2}" 
            wheel_joint_type="${wheel_joint_type}" />
        
        <wheel prefix="RF" X="${frontWheelX}" 
            Y="${-chassisWidth/2-wheelClearance-wheelWidth/2}"
            wheel_joint_type="${wheel_joint_type}" />

        <wheel prefix="LH" X="${backWheelX}" 
            Y="${chassisWidth/2+wheelClearance+wheelWidth/2}"
	    wheel_joint_type="${wheel_joint_type}" />

        <wheel prefix="RH" X="${backWheelX}" 
            Y="${-chassisWidth/2-wheelClearance-wheelWidth/2}"
            wheel_joint_type="${wheel_joint_type}" />
    </xacro:macro>
</robot>
