## This service saves the recorded log element data to
## files. The file types are specified by 'logfileTypes'.
## The files are saved and 'success' is set to true. Else
## 'success' is set to false and no action is taken.

# Save type
int8 LOGFILE_TYPE_BINARY=0
int8 LOGFILE_TYPE_CSV=1
int8 LOGFILE_TYPE_BAG=2
int8[] logfileTypes
---
bool success
