uint16 FULL_SHUTDOWN = 1                  # Full shutdown - the robot will fully power off
uint16 MOTORS_POWER_SHUTDOWN = 2          # Motors' power shutdown - Removes all electrical power to the motors
uint16 SMART_FULL_SHUTDOWN = 3            # Same as full shutdown, but robot moves to safe configuration first
uint16 SMART_MOTORS_POWER_SHUTDOWN = 4    # Same as Motors' power shutdown, but robot moves to safe configuration first
uint16 REST_MANEUVER = 5                  # Robot goes to rest (safe) configuration, but does not power off
uint16 STANDUP_MANEUVER = 6               # Robot goes to standup configuration
uint16 MOTORS_POWER_STARTUP = 7	          # Motor's power on - Powers the motors on
uint16 SMART_MOTORS_POWER_STARTUP = 8	  # Motor's power on - Powers the motors on and goes to standup configuration
uint16 type
---
bool success