# Option for usage of kindr (default: ON)
option(SILO_USE_KINDR "Use kindr in signal_logger?" ON)
if (SILO_USE_KINDR)
  MESSAGE(STATUS "Signal logger: Supporting kindr types!")
	add_definitions(-DSILO_USE_KINDR)
else(SILO_USE_KINDR)
  MESSAGE(STATUS "Signal logger: Exclude kindr types!")
endif(SILO_USE_KINDR)
